name: Update README

on:
  schedule:
    - cron: '*/1 * * * *' # Runs every 1 minute

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run script to update README
      run: python update_readme.py
      
    
